export const apiRoutes = {
  root: "/",
  health: "/health",
  auth: {
    me: "/api/auth/me",
    profile: "/api/auth/profile",
    changePassword: "/api/auth/change-password",
    register: "/api/auth/register",
    login: "/api/auth/login",
  },
  movies: {
    list: "/api/movies/",
    search: "/api/movies/search",
    detail: (movieId: number) => `/api/movies/${movieId}`,
    uploadPoster: "/api/movies/upload-poster",
  },
  bookings: {
    seats: (showId: number) => `/api/bookings/seats/${showId}`,
    book: "/api/bookings/book",
    userBookings: "/api/bookings/user/bookings",
    priceCalculation: "/api/bookings/price-calculation",
  },
  tickets: {
    pdf: (bookingId: number) => `/api/tickets/ticket/${bookingId}/pdf`,
  },
  admin: {
    theatres: "/api/admin/theatres",
    theatre: (theatreId: number) => `/api/admin/theatres/${theatreId}`,
    screens: "/api/admin/screens",
    screen: (screenId: number) => `/api/admin/screens/${screenId}`,
    pricing: "/api/admin/pricing",
    pricingById: (pricingId: number) => `/api/admin/pricing/${pricingId}`,
    pricingRules: "/api/admin/pricing/rules",
    pricingRule: (ruleId: number) => `/api/admin/pricing/rules/${ruleId}`,
    stats: "/api/admin/stats",
    revenueChart: "/api/admin/revenue-chart",
    bookingTrends: "/api/admin/booking-trends",
    bookings: "/api/admin/bookings",
    cancelBooking: (bookingId: number) => `/api/admin/bookings/${bookingId}/cancel`,
    booking: (bookingId: number) => `/api/admin/bookings/${bookingId}`,
    showStats: (showId: number) => `/api/admin/shows/${showId}/stats`,
    audit: "/api/admin/audit",
    health: "/api/admin/health",
  },
  schedule: {
    theatres: "/api/schedule/theatres",
    screens: "/api/schedule/screens",
    shows: "/api/schedule/shows",
    showsByMovie: (movieId: number) => `/api/schedule/shows/${movieId}`,
    allShows: "/api/schedule/shows/all/",
    show: (showId: number) => `/api/schedule/shows/show/${showId}`,
    deleteShow: (showId: number) => `/api/schedule/shows/${showId}`,
  },
  reviews: {
    create: "/api/reviews/",
    byMovie: (movieId: number) => `/api/reviews/movie/${movieId}`,
    all: "/api/reviews/all",
    delete: (reviewId: number) => `/api/reviews/${reviewId}`,
    update: (reviewId: number) => `/api/reviews/${reviewId}`,
  },
  reservations: {
    create: "/api/reservations",
    detail: (groupId: number) => `/api/reservations/${groupId}`,
    cancel: (groupId: number) => `/api/reservations/${groupId}`,
    confirm: (groupId: number) => `/api/reservations/${groupId}/confirm`,
    seatStatus: (showId: number) => `/api/shows/${showId}/seat-status`,
  },
  layouts: {
    generate: "/api/layouts/generate",
    save: "/api/layouts/save",
    screen: (screenId: number) => `/api/layouts/screen/${screenId}`,
    screenAll: (screenId: number) => `/api/layouts/screen/${screenId}/all`,
    detail: (layoutId: number) => `/api/layouts/${layoutId}`,
    publish: (layoutId: number) => `/api/layouts/${layoutId}/publish`,
    seats: (layoutId: number) => `/api/layouts/${layoutId}/seats`,
    stats: (layoutId: number) => `/api/layouts/${layoutId}/stats`,
    templates: "/api/layouts/templates/list",
    version: (layoutId: number) => `/api/layouts/${layoutId}/version`,
    rollback: (screenId: number) => `/api/layouts/screen/${screenId}/rollback`,
  },
} as const;
