"""initial_schema

Revision ID: 28d8862fe157
Revises: 
Create Date: 2026-05-27 18:28:58.269144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d8862fe157'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('medium_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_id'), 'media_assets', ['id'], unique=False)
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('running_days', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_table('theatres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('banner_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatres_id'), 'theatres', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_movie_id'), 'reviews', ['movie_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theatre_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('screen_type', sa.String(length=50), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('seat_layout_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screens_id'), 'screens', ['id'], unique=False)
    op.create_index(op.f('ix_screens_theatre_id'), 'screens', ['theatre_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('theatre_id', sa.Integer(), nullable=True),
    sa.Column('screen_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_id'), 'pricing_rules', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_rule_type'), 'pricing_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_pricing_rules_screen_id'), 'pricing_rules', ['screen_id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_theatre_id'), 'pricing_rules', ['theatre_id'], unique=False)
    op.create_table('seat_pricings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theatre_id', sa.Integer(), nullable=True),
    sa.Column('screen_id', sa.Integer(), nullable=True),
    sa.Column('seat_category', sa.String(length=50), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_pricings_id'), 'seat_pricings', ['id'], unique=False)
    op.create_index(op.f('ix_seat_pricings_screen_id'), 'seat_pricings', ['screen_id'], unique=False)
    op.create_index(op.f('ix_seat_pricings_seat_category'), 'seat_pricings', ['seat_category'], unique=False)
    op.create_index(op.f('ix_seat_pricings_theatre_id'), 'seat_pricings', ['theatre_id'], unique=False)
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('screen_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price_multiplier', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_date'), 'shows', ['date'], unique=False)
    op.create_index(op.f('ix_shows_id'), 'shows', ['id'], unique=False)
    op.create_index(op.f('ix_shows_movie_id'), 'shows', ['movie_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_date'), 'bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_movie_id'), 'bookings', ['movie_id'], unique=False)
    op.create_index(op.f('ix_bookings_show_id'), 'bookings', ['show_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('booked_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('seat_name', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booked_seats_booking_id'), 'booked_seats', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booked_seats_id'), 'booked_seats', ['id'], unique=False)
    op.create_index(op.f('ix_booked_seats_movie_id'), 'booked_seats', ['movie_id'], unique=False)
    op.create_index(op.f('ix_booked_seats_show_id'), 'booked_seats', ['show_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booked_seats_show_id'), table_name='booked_seats')
    op.drop_index(op.f('ix_booked_seats_movie_id'), table_name='booked_seats')
    op.drop_index(op.f('ix_booked_seats_id'), table_name='booked_seats')
    op.drop_index(op.f('ix_booked_seats_booking_id'), table_name='booked_seats')
    op.drop_table('booked_seats')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_show_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_movie_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_date'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_shows_movie_id'), table_name='shows')
    op.drop_index(op.f('ix_shows_id'), table_name='shows')
    op.drop_index(op.f('ix_shows_date'), table_name='shows')
    op.drop_table('shows')
    op.drop_index(op.f('ix_seat_pricings_theatre_id'), table_name='seat_pricings')
    op.drop_index(op.f('ix_seat_pricings_seat_category'), table_name='seat_pricings')
    op.drop_index(op.f('ix_seat_pricings_screen_id'), table_name='seat_pricings')
    op.drop_index(op.f('ix_seat_pricings_id'), table_name='seat_pricings')
    op.drop_table('seat_pricings')
    op.drop_index(op.f('ix_pricing_rules_theatre_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_screen_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_rule_type'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_screens_theatre_id'), table_name='screens')
    op.drop_index(op.f('ix_screens_id'), table_name='screens')
    op.drop_table('screens')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_movie_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_theatres_id'), table_name='theatres')
    op.drop_table('theatres')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_media_assets_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
