"""add_movie_status

Revision ID: 2faa24333e9b
Revises: a1b2c3d4e5f6
Create Date: 2026-06-27 21:32:48.542126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2faa24333e9b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('seat_definitions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('seat_definitions', 'is_couple')
    op.drop_column('seat_definitions', 'is_wheelchair')
    op.drop_column('seat_definitions', 'is_blocked')
    op.add_column('theatre_layouts', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('theatre_layouts', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('theatre_layouts', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.create_index(op.f('ix_theatre_layouts_status'), 'theatre_layouts', ['status'], unique=False)
    op.create_index(op.f('ix_theatre_layouts_version'), 'theatre_layouts', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theatre_layouts_version'), table_name='theatre_layouts')
    op.drop_index(op.f('ix_theatre_layouts_status'), table_name='theatre_layouts')
    op.alter_column('theatre_layouts', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('theatre_layouts', 'version')
    op.drop_column('theatre_layouts', 'status')
    op.add_column('seat_definitions', sa.Column('is_blocked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('seat_definitions', sa.Column('is_wheelchair', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('seat_definitions', sa.Column('is_couple', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('seat_definitions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('movies', 'status')
    # ### end Alembic commands ###
