"""add_media_asset_source_type

Revision ID: 3859385a4c2a
Revises: dae46307dfa6
Create Date: 2026-05-27 19:34:45.170108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3859385a4c2a'
down_revision: Union[str, Sequence[str], None] = 'dae46307dfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('media_assets', sa.Column('original_source_url', sa.String(length=1000), nullable=True))
    op.alter_column('media_assets', 'public_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('media_assets', 'thumbnail_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('media_assets', 'medium_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'medium_url',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('media_assets', 'thumbnail_url',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('media_assets', 'public_url',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('media_assets', 'original_source_url')
    op.drop_column('media_assets', 'source_type')
    # ### end Alembic commands ###
