"""add_movie_poster_fields_and_soft_delete

Revision ID: 5d89febe9b48
Revises: 3859385a4c2a
Create Date: 2026-06-17 12:38:27.379001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d89febe9b48'
down_revision: Union[str, Sequence[str], None] = '3859385a4c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOTE: modified before this migration's first real deployment (this
    project has never been deployed — see the "add_active_reservation_..."
    migration and project audit notes for how that was confirmed) to add
    `server_default` to both NOT NULL columns. Without a server default,
    `ADD COLUMN ... NOT NULL` fails under MySQL's default strict SQL mode as
    soon as the `movies` table has any existing rows, since MySQL has no
    value to backfill them with. Defaults match the SQLAlchemy model
    (backend/models/movie.py): poster_source_type defaults to "upload",
    is_deleted defaults to False.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'movies',
        sa.Column('poster_source_type', sa.String(length=50), nullable=False, server_default='upload'),
    )
    op.add_column('movies', sa.Column('poster_uploaded_at', sa.DateTime(), nullable=True))
    op.add_column(
        'movies',
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('movies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'deleted_at')
    op.drop_column('movies', 'is_deleted')
    op.drop_column('movies', 'poster_uploaded_at')
    op.drop_column('movies', 'poster_source_type')
    # ### end Alembic commands ###
