"""add_reservations

Revision ID: e3a447ad0bf6
Revises: 5d89febe9b48
Create Date: 2026-06-18 20:09:25.979950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a447ad0bf6'
down_revision: Union[str, Sequence[str], None] = '5d89febe9b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('reservation_token', sa.String(length=100), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_groups_expires_at'), 'reservation_groups', ['expires_at'], unique=False)
    op.create_index(op.f('ix_reservation_groups_id'), 'reservation_groups', ['id'], unique=False)
    op.create_index(op.f('ix_reservation_groups_show_id'), 'reservation_groups', ['show_id'], unique=False)
    op.create_index(op.f('ix_reservation_groups_status'), 'reservation_groups', ['status'], unique=False)
    op.create_index(op.f('ix_reservation_groups_user_id'), 'reservation_groups', ['user_id'], unique=False)
    op.create_table('seat_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_group_id', sa.Integer(), nullable=True),
    sa.Column('seat_id', sa.String(length=10), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_group_id'], ['reservation_groups.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_reservations_id'), 'seat_reservations', ['id'], unique=False)
    op.create_index(op.f('ix_seat_reservations_reservation_group_id'), 'seat_reservations', ['reservation_group_id'], unique=False)
    op.create_index(op.f('ix_seat_reservations_seat_id'), 'seat_reservations', ['seat_id'], unique=False)
    op.create_index(op.f('ix_seat_reservations_show_id'), 'seat_reservations', ['show_id'], unique=False)
    op.create_index(op.f('ix_seat_reservations_status'), 'seat_reservations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_reservations_status'), table_name='seat_reservations')
    op.drop_index(op.f('ix_seat_reservations_show_id'), table_name='seat_reservations')
    op.drop_index(op.f('ix_seat_reservations_seat_id'), table_name='seat_reservations')
    op.drop_index(op.f('ix_seat_reservations_reservation_group_id'), table_name='seat_reservations')
    op.drop_index(op.f('ix_seat_reservations_id'), table_name='seat_reservations')
    op.drop_table('seat_reservations')
    op.drop_index(op.f('ix_reservation_groups_user_id'), table_name='reservation_groups')
    op.drop_index(op.f('ix_reservation_groups_status'), table_name='reservation_groups')
    op.drop_index(op.f('ix_reservation_groups_show_id'), table_name='reservation_groups')
    op.drop_index(op.f('ix_reservation_groups_id'), table_name='reservation_groups')
    op.drop_index(op.f('ix_reservation_groups_expires_at'), table_name='reservation_groups')
    op.drop_table('reservation_groups')
    # ### end Alembic commands ###
