"""Idempotent, additive catalog seeder for a realistic multi-city demo dataset.

This is DELIBERATELY SEPARATE from scripts/seed_db.py (which stays as the
minimal admin-bootstrap + tiny smoke-test dataset it always was). This script
seeds a much larger, real-world catalog: verified Indian cinema venues and a
curated Hollywood/Indian-language movie library, plus the application-
generated operational data (layouts, seats, pricing, shows) needed to make
it actually bookable.

DATA PROVENANCE
----------------
Theatre/movie identity and metadata below were verified via live web
research on 2026-08-29 (see docs/SEEDED_DATA_SOURCES.md for the full
per-entity source list and verification notes). Anything not independently
verifiable was left out rather than invented — see the SOURCES doc for the
explicit list of what was excluded and why.

Everything else generated by this script (seat layouts, seat definitions,
seat pricing, show schedule) is APPLICATION-GENERATED OPERATIONAL DATA
associated with a real venue — it is not, and must not be presented as,
the venue's actual physical seating arrangement.

IDEMPOTENCY
------------
Every insert is gated by a natural-key existence check:
  Movie:   (title, release_date)
  Theatre: (name, city)
  Screen:  (theatre_id, name)
  Show:    (screen_id, movie_id, date, start_time)
Re-running this script only adds what's missing. It never touches Booking
or User records, and never deletes anything except the synthetic
"Grand Plaza Cinema" placeholder — and only after confirming it has no
booking dependencies (see handle_synthetic_placeholder()).

USAGE
------
    python scripts/seed_demo_catalog.py
"""
import os
import sys
from dotenv import load_dotenv

load_dotenv()
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from datetime import date, datetime, timedelta
from typing import Dict, List, Optional, Tuple

from sqlalchemy.orm import Session

from backend.database import SessionLocal, engine, Base
from backend.models import models
from backend.utils.layout_generator import generate_layout


# ─────────────────────────────────────────────────────────────────────────
# THEATRES (verified 2026-08-29 — see docs/SEEDED_DATA_SOURCES.md)
# ─────────────────────────────────────────────────────────────────────────
# Screen tech labels are only ever set when a source explicitly verified
# that screen's technology for that specific venue. Where a real venue has
# more verified screens than we seed here, we've capped the count to a
# representative subset (never claiming the venue has FEWER screens than
# it does — just seeding a manageable slice) while always keeping any
# individually-named verified premium screen.
#
# seat_tier -> generate_layout() template + operational (non-verified)
# capacity estimate. See PHASE 5 rules: seat geometry is demo/operational
# data, never a claim about the venue's real physical seating.
SEAT_TIERS = {
    "premium_large": {"template": "IMAX", "total_seats": 280},
    "luxury_recliner": {"template": "RECLINER", "total_seats": 90},
    "standard": {"template": "STANDARD", "total_seats": 180},
    "compact": {"template": "STANDARD", "total_seats": 150},
}

# Screen technology labels that count as "premium_large" / "luxury_recliner"
PREMIUM_LARGE_TYPES = {"IMAX", "IMAX Laser", "4DX", "PXL", "PCX Large Format"}
LUXURY_RECLINER_TYPES = {"Gold Class", "LUXE"}


def _screen(name: str, screen_type: str = "Standard", total_seats: Optional[int] = None) -> Dict:
    if total_seats is not None:
        tier_seats = total_seats
    elif screen_type in PREMIUM_LARGE_TYPES:
        tier_seats = SEAT_TIERS["premium_large"]["total_seats"]
    elif screen_type in LUXURY_RECLINER_TYPES:
        tier_seats = SEAT_TIERS["luxury_recliner"]["total_seats"]
    else:
        tier_seats = SEAT_TIERS["standard"]["total_seats"]
    return {"name": name, "screen_type": screen_type, "total_seats": tier_seats}


THEATRES: List[Dict] = [
    # ── Chennai ──────────────────────────────────────────────────────────
    {
        "name": "PVR ICON, VR Chennai",
        "city": "Chennai", "state": "Tamil Nadu", "timezone": "Asia/Kolkata",
        "address": "VR Mall, Jawaharlal Nehru Road, Anna Nagar",
        "description": "PVR multiplex at VR Chennai mall, Anna Nagar.",
        "screens": [
            _screen("P[XL] Laser Screen", "PXL"),
            _screen("Screen 2"), _screen("Screen 3"), _screen("Screen 4"),
        ],
    },
    {
        "name": "PVR Palazzo, Forum Vijaya Mall",
        "city": "Chennai", "state": "Tamil Nadu", "timezone": "Asia/Kolkata",
        "address": "Forum Vijaya Mall, Vadapalani",
        "description": "PVR multiplex (originally SPI Cinemas' Palazzo) at Forum Vijaya Mall, Vadapalani.",
        "screens": [
            _screen("IMAX Screen", "IMAX"),
            _screen("Screen 2"), _screen("Screen 3"), _screen("Screen 4"),
        ],
    },
    {
        "name": "AGS Cinemas, Villivakkam",
        "city": "Chennai", "state": "Tamil Nadu", "timezone": "Asia/Kolkata",
        "address": "Mettu Street, Behind Villivakkam Bus Depot",
        "description": "AGS Cinemas multiplex, Villivakkam.",
        "screens": [_screen(f"Screen {i}", total_seats=SEAT_TIERS["compact"]["total_seats"]) for i in range(1, 6)],
    },
    # ── Bengaluru ────────────────────────────────────────────────────────
    {
        "name": "PVR Nexus Koramangala",
        "city": "Bengaluru", "state": "Karnataka", "timezone": "Asia/Kolkata",
        "address": "Nexus Mall (formerly Forum Mall), Hosur Road, Koramangala",
        "description": "PVR's first-ever IMAX screen in India (now 4K laser), plus 4DX and Gold Class.",
        "screens": [
            _screen("IMAX Screen (4K Laser)", "IMAX Laser"),
            _screen("4DX Screen", "4DX"),
            _screen("Gold Class Screen", "Gold Class"),
            _screen("Screen 4"),
        ],
    },
    {
        "name": "PVR Orion Mall, Rajajinagar",
        "city": "Bengaluru", "state": "Karnataka", "timezone": "Asia/Kolkata",
        "address": "Orion Mall at Brigade Gateway, Dr Rajkumar Road, Rajajinagar",
        "description": "PVR multiplex at Orion Mall, Rajajinagar.",
        "screens": [
            _screen("PXL Screen", "PXL"),
            _screen("4DX Screen", "4DX"),
            _screen("Screen 3"), _screen("Screen 4"),
        ],
    },
    # ── Hyderabad ────────────────────────────────────────────────────────
    {
        "name": "Prasads Multiplex",
        "city": "Hyderabad", "state": "Telangana", "timezone": "Asia/Kolkata",
        "address": "IMAX Road, NTR Marg, Necklace Road, Khairtabad",
        "description": "Independent multiplex; Screen 6 is a large-format 'PCX' screen (not IMAX-branded since 2014).",
        "screens": [
            _screen("Screen 1"), _screen("Screen 2"), _screen("Screen 3"),
            _screen("Screen 4"), _screen("Screen 5"),
            _screen("Screen 6 (PCX Large Format)", "PCX Large Format"),
        ],
    },
    {
        "name": "AAA Cinemas, Ameerpet",
        "city": "Hyderabad", "state": "Telangana", "timezone": "Asia/Kolkata",
        "address": "Asian Satyam Mall, Satyam Theatre Rd, Ameerpet",
        "description": "Asian Cinemas multiplex in partnership with Allu Arjun.",
        "screens": [
            _screen("Screen 1 (Barco Laser, Dolby Atmos)", "IMAX Laser", total_seats=SEAT_TIERS["premium_large"]["total_seats"]),
            _screen("Screen 2 (EPIQ Luxon, Dolby Atmos)", "Dolby Atmos", total_seats=SEAT_TIERS["standard"]["total_seats"]),
            _screen("Screen 3"), _screen("Screen 4"), _screen("Screen 5"),
        ],
    },
    # ── Kochi ────────────────────────────────────────────────────────────
    {
        "name": "PVR Lulu, Edappally",
        "city": "Kochi", "state": "Kerala", "timezone": "Asia/Kolkata",
        "address": "Lulu International Shopping Mall, Edappally",
        "description": "PVR multiplex at Lulu Mall, Edappally (no IMAX at this location).",
        "screens": [
            _screen("Gold Class Screen", "Gold Class"),
            _screen("4DX Screen", "4DX"),
            _screen("Screen 3"), _screen("Screen 4"),
        ],
    },
    {
        "name": "PVR Oberon Mall, Edappally",
        "city": "Kochi", "state": "Kerala", "timezone": "Asia/Kolkata",
        "address": "Oberon Mall, Mosque Road, NH Bypass, Padivattom, Edappally",
        "description": "PVR multiplex (originally Cinemax, Kerala's first multiplex) at Oberon Mall.",
        "screens": [_screen(f"Screen {i}", "Dolby Atmos") for i in range(1, 5)],
    },
    # ── Coimbatore ───────────────────────────────────────────────────────
    {
        "name": "Cinepolis, Fun Republic Mall",
        "city": "Coimbatore", "state": "Tamil Nadu", "timezone": "Asia/Kolkata",
        "address": "Fun Republic Mall, Avinashi Road, Peelamedu",
        "description": "Cinepolis multiplex at Fun Republic Mall, Peelamedu.",
        "screens": [_screen(f"Screen {i}") for i in range(1, 6)],
    },
    # ── Visakhapatnam ────────────────────────────────────────────────────
    {
        "name": "Miraj Cinemas, Bhupathi Surya Central",
        "city": "Visakhapatnam", "state": "Andhra Pradesh", "timezone": "Asia/Kolkata",
        "address": "Bhupathi Surya Central Mall",
        "description": "Miraj Cinemas multiplex, Visakhapatnam.",
        "screens": [_screen(f"Screen {i}") for i in range(1, 5)],
    },
    {
        "name": "INOX, CMR Central",
        "city": "Visakhapatnam", "state": "Andhra Pradesh", "timezone": "Asia/Kolkata",
        "address": "CMR Central Mall, Maddilapalem",
        "description": "First INOX in Visakhapatnam, at CMR Central Mall.",
        "screens": [_screen(f"Screen {i}") for i in range(1, 5)],
    },
    # ── Mumbai ───────────────────────────────────────────────────────────
    {
        "name": "PVR, Phoenix Marketcity",
        "city": "Mumbai", "state": "Maharashtra", "timezone": "Asia/Kolkata",
        "address": "Phoenix Marketcity Mall, LBS Marg, Kurla West",
        "description": "PVR multiplex at Phoenix Marketcity, Kurla West.",
        "screens": [_screen(f"Screen {i}") for i in range(1, 5)],
    },
    # ── Delhi ────────────────────────────────────────────────────────────
    {
        "name": "INOX, Nehru Place",
        "city": "New Delhi", "state": "Delhi", "timezone": "Asia/Kolkata",
        "address": "District Centre, near Intercontinental Hotel, Nehru Place",
        "description": "INOX multiplex at Nehru Place District Centre.",
        "screens": [_screen(f"Screen {i}") for i in range(1, 6)],
    },
    {
        "name": "PVR Priya, Vasant Vihar",
        "city": "New Delhi", "state": "Delhi", "timezone": "Asia/Kolkata",
        "address": "Basant Lok Community Centre, Vasant Vihar",
        "description": "Historic standalone cinema (founding site of the PVR brand, 1997), now a single-screen IMAX-with-laser theatre.",
        "screens": [_screen("IMAX Laser Screen", "IMAX Laser")],
    },
    # ── Noida / NCR ──────────────────────────────────────────────────────
    {
        "name": "PVR Superplex, Logix City Centre",
        "city": "Noida", "state": "Uttar Pradesh", "timezone": "Asia/Kolkata",
        "address": "Logix City Centre Mall, Sector 32",
        "description": "PVR Superplex with the largest IMAX screen in the NCR region, plus 4DX, PXL, and Gold Class.",
        "screens": [
            _screen("IMAX Screen (Largest in NCR)", "IMAX"),
            _screen("4DX Screen", "4DX"),
            _screen("PXL Screen", "PXL"),
            _screen("Gold Class Screen", "Gold Class"),
        ],
    },
    # ── Pune ─────────────────────────────────────────────────────────────
    {
        "name": "City Pride Multiplex, Kothrud",
        "city": "Pune", "state": "Maharashtra", "timezone": "Asia/Kolkata",
        "address": "Near Gandhi Lawns, Kothrud",
        "description": "Independent regional multiplex chain; Dolby digital sound, recliner seating.",
        "screens": [_screen(f"Screen {i}", "Dolby Atmos") for i in range(1, 5)],
    },
    # ── Kolkata ──────────────────────────────────────────────────────────
    {
        "name": "Nandan",
        "city": "Kolkata", "state": "West Bengal", "timezone": "Asia/Kolkata",
        "address": "1/1 AJC Bose Road",
        "description": "Government of West Bengal art-house cinema, inaugurated by Satyajit Ray in 1985.",
        "screens": [
            _screen("Nandan I", total_seats=SEAT_TIERS["premium_large"]["total_seats"]),
            _screen("Nandan II", total_seats=SEAT_TIERS["standard"]["total_seats"]),
            _screen("Nandan III", total_seats=SEAT_TIERS["compact"]["total_seats"]),
        ],
    },
    # ── Ahmedabad ────────────────────────────────────────────────────────
    {
        "name": "Cinepolis, Alpha One Mall",
        "city": "Ahmedabad", "state": "Gujarat", "timezone": "Asia/Kolkata",
        "address": "Alpha One Mall (Nexus Ahmedabad One), Vastrapur",
        "description": "Cinepolis multiplex, Alpha One Mall; Dolby 7.1 and RealD 3D.",
        "screens": [_screen(f"Screen {i}", "Dolby Atmos") for i in range(1, 5)],
    },
    # ── Jaipur ───────────────────────────────────────────────────────────
    {
        "name": "Raj Mandir Cinema",
        "city": "Jaipur", "state": "Rajasthan", "timezone": "Asia/Kolkata",
        "address": "Panch Batti",
        "description": "Iconic independent single-screen cinema, opened June 1, 1976.",
        "screens": [_screen("Main Auditorium", "Standard", total_seats=854)],
    },
    # ── Lucknow ──────────────────────────────────────────────────────────
    {
        "name": "PVR Superplex, Lulu Mall",
        "city": "Lucknow", "state": "Uttar Pradesh", "timezone": "Asia/Kolkata",
        "address": "Lulu Mall",
        "description": "11-screen PVR Superplex (opened March 2023) with 4DX, PXL, and two LUXE auditoriums.",
        "screens": [
            _screen("4DX Screen", "4DX"),
            _screen("PXL Screen", "PXL"),
            _screen("LUXE Screen 1", "LUXE"),
            _screen("LUXE Screen 2", "LUXE"),
        ],
    },
    # ── Chandigarh ───────────────────────────────────────────────────────
    {
        "name": "PVR, Elante Mall",
        "city": "Chandigarh", "state": "Chandigarh", "timezone": "Asia/Kolkata",
        "address": "Elante Mall, Industrial Area Phase-1",
        "description": "PVR multiplex at Elante Mall, with IMAX and 4DX screens.",
        "screens": [
            _screen("IMAX Screen", "IMAX"),
            _screen("4DX Screen", "4DX"),
            _screen("Screen 3"), _screen("Screen 4"),
        ],
    },
]


# ─────────────────────────────────────────────────────────────────────────
# MOVIES (verified 2026-08-29 — see docs/SEEDED_DATA_SOURCES.md)
# ─────────────────────────────────────────────────────────────────────────
# poster_url is intentionally left None everywhere: no TMDB poster hash was
# independently verified during research, and PHASE 7 rules forbid using an
# unverified/guessed image URL. rating is None where a source figure could
# not be confirmed live (never guessed).
def _movie(title, language, genre, release_date, duration, rating=None, description=""):
    return {
        "title": title, "language": language, "genre": genre,
        "release_date": release_date, "duration": duration,
        "rating": rating, "description": description,
    }


MOVIES: List[Dict] = [
    # ── Hollywood — Classic ──────────────────────────────────────────────
    _movie("The Godfather", "English", "Crime", date(1972, 3, 24), 175, 9.2,
           "An aging mafia patriarch transfers control of his empire to his reluctant son."),
    _movie("The Matrix", "English", "Sci-Fi", date(1999, 3, 31), 136, 8.7,
           "A hacker discovers reality is a simulation and joins a rebellion against machine overlords."),
    _movie("Titanic", "English", "Romance", date(1997, 12, 19), 195, 7.9,
           "A penniless artist and a wealthy young woman fall in love aboard the ill-fated ocean liner."),
    _movie("Jurassic Park", "English", "Adventure", date(1993, 6, 11), 127, 8.2,
           "A theme park of cloned dinosaurs spirals into chaos when the creatures escape containment."),
    _movie("The Dark Knight", "English", "Action", date(2008, 7, 18), 152, 9.1,
           "Batman faces the anarchic Joker in a battle that pushes Gotham's heroes to their limits."),
    _movie("Inception", "English", "Sci-Fi", date(2010, 7, 16), 148, 8.8,
           "A skilled thief who invades dreams is offered a chance at redemption via an impossible heist."),
    _movie("Interstellar", "English", "Sci-Fi", date(2014, 11, 7), 169, 8.7,
           "A team of astronauts travels through a wormhole seeking a new home for humanity."),
    _movie("Top Gun: Maverick", "English", "Action", date(2022, 5, 25), 131, 8.3,
           "A veteran fighter pilot confronts his past while training a new generation for an impossible mission."),
    # ── Hollywood — Current/Recent ───────────────────────────────────────
    _movie("Barbie", "English", "Comedy", date(2023, 7, 21), 114, 6.8,
           "A doll living in an idealized world sets out on a journey of self-discovery into the real world."),
    _movie("Oppenheimer", "English", "Biography", date(2023, 7, 21), 180, 8.2,
           "The story of physicist J. Robert Oppenheimer and his role in developing the atomic bomb."),
    _movie("Dune: Part Two", "English", "Sci-Fi", date(2024, 3, 1), 166, 8.5,
           "Paul Atreides unites with the Fremen to seek revenge against those who destroyed his family."),
    _movie("Deadpool & Wolverine", "English", "Action", date(2024, 7, 26), 128, 7.5,
           "A mercenary with a healing factor recruits a reluctant Wolverine variant to save his universe."),
    _movie("Inside Out 2", "English", "Animation", date(2024, 6, 11), 100, 7.5,
           "As a teenager, Riley's mind acquires new emotions, disrupting the balance of her inner world."),
    _movie("Twisters", "English", "Action", date(2024, 7, 19), 122, None,
           "A former storm chaser is drawn back into tornado research when a new team's methods upend the field."),
    _movie("Wicked", "English", "Fantasy", date(2024, 11, 22), 160, 7.3,
           "The untold origin story of Elphaba, the future Wicked Witch of the West."),
    _movie("Sinners", "English", "Horror", date(2025, 4, 18), 138, 8.2,
           "Twin brothers return to their Mississippi hometown, only to confront a supernatural evil."),
    _movie("A Minecraft Movie", "English", "Comedy", date(2025, 4, 4), 101, 5.6,
           "Four misfits are pulled through a portal into the blocky Overworld and must find their way home."),
    _movie("F1: The Movie", "English", "Sport", date(2025, 6, 27), 155, 7.6,
           "A washed-up former F1 driver returns to mentor a rookie teammate on a struggling racing team."),
    _movie("Superman", "English", "Action", date(2025, 7, 11), 129, 7.0,
           "A young Superman balances his Kryptonian heritage with his human upbringing."),
    _movie("Mission: Impossible - The Final Reckoning", "English", "Action", date(2025, 5, 23), 170, 7.2,
           "Ethan Hunt races against a rogue AI in his final mission to save the world."),
    _movie("Zootopia 2", "English", "Animation", date(2025, 11, 26), 107, 7.4,
           "Detectives Judy Hopps and Nick Wilde reunite to crack a new case that shakes Zootopia."),
    _movie("Avatar: Fire and Ash", "English", "Sci-Fi", date(2025, 12, 19), 195, 7.6,
           "Jake Sully and Neytiri's family confronts a fierce new Na'vi clan tied to fire."),
    _movie("Spider-Man: Brand New Day", "English", "Action", date(2026, 7, 31), 145, 8.2,
           "Peter Parker fights crime in a world that's forgotten Spider-Man ever existed."),
    # ── Hollywood — Upcoming ─────────────────────────────────────────────
    _movie("Avengers: Doomsday", "English", "Action", date(2026, 12, 18), None, None,
           "Earth's mightiest heroes unite against a multiversal threat tied to Victor von Doom."),
    _movie("Avengers: Secret Wars", "English", "Action", date(2027, 12, 17), None, None,
           "The Avengers face a reality-altering crisis that threatens to collapse the multiverse."),
    _movie("The Batman: Part II", "English", "Action", date(2028, 2, 18), None, None,
           "Robert Pattinson's Batman returns to confront a new threat rising from Gotham's underworld."),

    # ── Indian — Classic ─────────────────────────────────────────────────
    _movie("Sholay", "Hindi", "Action", date(1975, 8, 15), 162, 8.1,
           "Two small-time criminals are hired to capture the ruthless bandit who murdered a retired officer's family."),
    _movie("Nayakan", "Tamil", "Crime", date(1987, 10, 21), 145, 8.6,
           "A smuggler's son rises to become a powerful, morally complex Mumbai don."),
    _movie("Baasha", "Tamil", "Action", date(1995, 1, 12), 145, 8.3,
           "A mild-mannered Chennai auto-rickshaw driver conceals a violent past as a feared Mumbai gangster."),
    _movie("Dilwale Dulhania Le Jayenge", "Hindi", "Romance", date(1995, 10, 20), 181, 8.0,
           "Two young NRIs fall in love on a European trip, then must win over her traditional family."),
    _movie("Lagaan", "Hindi", "Drama", date(2001, 6, 15), 224, 8.1,
           "Villagers under British colonial rule wager their harvest tax on a high-stakes cricket match."),
    _movie("Magadheera", "Telugu", "Action", date(2009, 7, 31), 158, 7.7,
           "A modern-day man discovers he is the reincarnation of a warrior bound by a centuries-old vendetta."),
    _movie("3 Idiots", "Hindi", "Comedy", date(2009, 12, 25), 170, 8.4,
           "Two friends search for their long-lost, free-spirited engineering-college classmate."),
    _movie("Drishyam", "Malayalam", "Thriller", date(2013, 12, 19), 164, 8.4,
           "A cable-TV operator uses his obsession with cinema to cover up a crime committed by his family."),
    _movie("Kantara", "Kannada", "Drama", date(2022, 9, 30), 148, None,
           "A village in coastal Karnataka clashes with authorities over sacred forest land tied to a folk deity."),
    # ── Indian — Current/Recent ──────────────────────────────────────────
    _movie("Manjummel Boys", "Malayalam", "Adventure", date(2024, 2, 22), 135, 8.2,
           "A group of friends on a trip must rescue one of their own after he falls into a deep cave."),
    _movie("Kalki 2898 AD", "Telugu", "Sci-Fi", date(2024, 6, 27), None, 7.0,
           "In a dystopian future, a bounty hunter is sent to capture a woman whose unborn child holds humanity's key."),
    _movie("Stree 2: Sarkate Ka Aatank", "Hindi", "Comedy", date(2024, 8, 15), None, 6.9,
           "The residents of Chanderi face a new supernatural menace even more dangerous than the original."),
    _movie("Pushpa 2: The Rule", "Telugu", "Action", date(2024, 12, 5), 201, 6.1,
           "A red-sandalwood smuggler's rise to power draws intensifying heat from a relentless police officer."),
    _movie("Sitaare Zameen Par", "Hindi", "Comedy", date(2025, 6, 20), 158, 6.9,
           "A disgraced basketball coach is assigned to train a team of neurodivergent adult players."),
    _movie("Thug Life", "Tamil", "Action", date(2025, 6, 5), 163, 4.4,
           "A gang leader's return from hiding reignites old betrayals within his crime family."),
    _movie("Kannappa", "Telugu", "Fantasy", date(2025, 6, 27), 182, 5.0,
           "A skilled hunter's devotion transforms him into one of Lord Shiva's most revered disciples."),
    _movie("Coolie", "Tamil", "Action", date(2025, 8, 14), 170, None,
           "A retired dockworker is pulled back into a dangerous underworld conspiracy after a friend's death."),
    _movie("Lokah Chapter 1: Chandra", "Malayalam", "Fantasy", date(2025, 8, 28), 150, 7.6,
           "A mysterious woman with supernatural powers becomes entangled with a group of ordinary people in Bengaluru."),
    _movie("Kantara: Chapter 1", "Kannada", "Action", date(2025, 10, 2), None, 8.1,
           "A prequel exploring the mythic origins of the sacred forest guardianship introduced in 'Kantara.'"),
    _movie("Toxic", "Kannada", "Action", date(2026, 8, 26), None, None,
           "A big-budget crime saga centered on a morally ambiguous antihero."),
    # ── Indian — Upcoming ────────────────────────────────────────────────
    _movie("Jailer 2", "Tamil", "Action", date(2026, 10, 15), None, None,
           "Sequel to the 2023 hit; a retired jailer is pulled back into action against a new criminal syndicate."),
    _movie("Spirit", "Telugu", "Action", date(2027, 3, 5), None, None,
           "A troubled cop confronts personal demons while taking down a global crime network."),
]


# Language -> cities where that language's films get show presence.
# English (Hollywood) is treated as broadly national. This mirrors PHASE 9's
# "don't force every movie into every city" instruction.
LANGUAGE_CITY_AFFINITY: Dict[str, List[str]] = {
    "English": ["Mumbai", "New Delhi", "Noida", "Bengaluru", "Chennai", "Hyderabad", "Pune", "Chandigarh"],
    "Hindi": ["Mumbai", "New Delhi", "Noida", "Pune", "Jaipur", "Lucknow", "Chandigarh", "Kolkata"],
    "Tamil": ["Chennai", "Coimbatore"],
    "Telugu": ["Hyderabad", "Visakhapatnam"],
    "Malayalam": ["Kochi"],
    "Kannada": ["Bengaluru"],
}

SHOW_TIME_SLOTS = ["10:00", "13:30", "17:00", "20:30"]


# ─────────────────────────────────────────────────────────────────────────
# Synthetic placeholder handling
# ─────────────────────────────────────────────────────────────────────────
def handle_synthetic_placeholder(db: Session) -> None:
    """Safely remove the earlier synthetic 'Grand Plaza Cinema' placeholder
    (fake venue, fake city 'Metropolis, NY') that scripts/seed_db.py used to
    create — but ONLY if nothing depends on it. This never runs raw/destructive
    SQL and never touches Booking/User records; it only ever inspects and,
    if safe, removes rows this same seeding architecture created.
    """
    placeholder = (
        db.query(models.Theatre)
        .filter(models.Theatre.name == "Grand Plaza Cinema", models.Theatre.city == "Metropolis")
        .first()
    )
    if not placeholder:
        return

    screen_ids = [s.id for s in db.query(models.Screen).filter(models.Screen.theatre_id == placeholder.id).all()]
    show_ids = [
        sh.id for sh in db.query(models.Show).filter(models.Show.screen_id.in_(screen_ids)).all()
    ] if screen_ids else []
    dependent_bookings = (
        db.query(models.Booking).filter(models.Booking.show_id.in_(show_ids)).count()
        if show_ids else 0
    )

    if dependent_bookings > 0:
        print(
            f"[SEED WARNING] 'Grand Plaza Cinema' has {dependent_bookings} dependent booking(s) — "
            "NOT deleting. Marking inactive instead so it drops out of customer-facing listings. "
            "Review these bookings manually before any further cleanup."
        )
        placeholder.is_active = False
        db.flush()
        return

    print("[SEED] Removing synthetic 'Grand Plaza Cinema' placeholder (no dependent bookings found)...")
    for screen_id in screen_ids:
        layout_ids = [
            l.id for l in db.query(models.TheatreLayout.id).filter(models.TheatreLayout.screen_id == screen_id).all()
        ]
        if layout_ids:
            db.query(models.SeatDefinition).filter(
                models.SeatDefinition.layout_id.in_(layout_ids)
            ).delete(synchronize_session=False)
            db.query(models.TheatreLayout).filter(
                models.TheatreLayout.id.in_(layout_ids)
            ).delete(synchronize_session=False)
        db.query(models.SeatPricing).filter(models.SeatPricing.screen_id == screen_id).delete(synchronize_session=False)
        db.query(models.Show).filter(models.Show.screen_id == screen_id).delete(synchronize_session=False)
    db.query(models.SeatPricing).filter(
        models.SeatPricing.theatre_id == placeholder.id, models.SeatPricing.screen_id.is_(None)
    ).delete(synchronize_session=False)
    db.query(models.Screen).filter(models.Screen.theatre_id == placeholder.id).delete(synchronize_session=False)
    db.delete(placeholder)
    db.flush()
    print("  ✓ Synthetic placeholder removed.")


# ─────────────────────────────────────────────────────────────────────────
# Theatres, screens, layouts, pricing
# ─────────────────────────────────────────────────────────────────────────
def get_or_create_theatre(db: Session, spec: Dict) -> models.Theatre:
    existing = (
        db.query(models.Theatre)
        .filter(models.Theatre.name == spec["name"], models.Theatre.city == spec["city"])
        .first()
    )
    if existing:
        return existing
    theatre = models.Theatre(
        name=spec["name"], city=spec["city"], state=spec["state"],
        timezone=spec["timezone"], address=spec["address"],
        description=spec["description"], is_active=True,
    )
    db.add(theatre)
    db.flush()
    print(f"  ✓ Theatre created: {theatre.name} ({theatre.city})")
    return theatre


def get_or_create_screen(db: Session, theatre: models.Theatre, spec: Dict) -> models.Screen:
    existing = (
        db.query(models.Screen)
        .filter(models.Screen.theatre_id == theatre.id, models.Screen.name == spec["name"])
        .first()
    )
    if existing:
        return existing
    screen = models.Screen(
        theatre_id=theatre.id, name=spec["name"], screen_type=spec["screen_type"],
        total_seats=spec["total_seats"], is_active=True,
    )
    db.add(screen)
    db.flush()
    return screen


def _layout_template_for(screen: models.Screen) -> str:
    if screen.screen_type in PREMIUM_LARGE_TYPES:
        return "IMAX"
    if screen.screen_type in LUXURY_RECLINER_TYPES:
        return "RECLINER"
    return "STANDARD"


def ensure_published_layout(db: Session, screen: models.Screen) -> None:
    """Reuses layout_generator.py + TheatreLayout/SeatDefinition — the same
    architecture as the admin Layout Designer and scripts/seed_db.py.
    Idempotent: no-op if a published layout already exists for this screen.
    """
    existing = (
        db.query(models.TheatreLayout)
        .filter(models.TheatreLayout.screen_id == screen.id, models.TheatreLayout.status == "published")
        .first()
    )
    if existing:
        return

    template = _layout_template_for(screen)
    layout_data = generate_layout(total_seats=screen.total_seats, template=template)

    layout = models.TheatreLayout(
        theatre_id=screen.theatre_id, screen_id=screen.id,
        layout_name="Default Layout", layout_type=template,
        total_seats=layout_data.total_seats, rows=layout_data.rows, cols=layout_data.cols,
        status="published", version=1, is_published=True,
    )
    db.add(layout)
    db.flush()

    for seat in layout_data.seats:
        db.add(models.SeatDefinition(
            layout_id=layout.id, seat_code=seat.seat_code, row_label=seat.row_label,
            seat_number=seat.seat_number, seat_type=seat.seat_type, category=seat.category,
            position_x=seat.position_x, position_y=seat.position_y, is_active=seat.is_active,
        ))
    db.flush()


# City tier -> base price table (application-generated operational pricing,
# not a claim about the venue's real ticket prices). Metro tier-1 cities get
# a modestly higher base than tier-2 cities, which is realistic behavior for
# Indian multiplex pricing without asserting a specific verified figure.
TIER1_CITIES = {"Mumbai", "New Delhi", "Noida", "Bengaluru", "Chennai", "Hyderabad"}
BASE_PRICES = {
    "tier1": {"Normal": 180.0, "Executive": 260.0, "Premium": 360.0},
    "tier2": {"Normal": 150.0, "Executive": 220.0, "Premium": 300.0},
}
PREMIUM_SCREEN_MULTIPLIER = 1.4


def ensure_seat_pricing(db: Session, theatre: models.Theatre, screens: List[models.Screen]) -> None:
    tier = "tier1" if theatre.city in TIER1_CITIES else "tier2"
    base = BASE_PRICES[tier]

    existing_theatre_wide = (
        db.query(models.SeatPricing)
        .filter(models.SeatPricing.theatre_id == theatre.id, models.SeatPricing.screen_id.is_(None))
        .first()
    )
    if not existing_theatre_wide:
        for category, price in base.items():
            db.add(models.SeatPricing(
                theatre_id=theatre.id, screen_id=None, seat_category=category, base_price=price,
            ))
        db.flush()

    for screen in screens:
        if screen.screen_type not in PREMIUM_LARGE_TYPES and screen.screen_type not in LUXURY_RECLINER_TYPES:
            continue
        existing_override = (
            db.query(models.SeatPricing)
            .filter(models.SeatPricing.theatre_id == theatre.id, models.SeatPricing.screen_id == screen.id)
            .first()
        )
        if existing_override:
            continue
        for category, price in base.items():
            db.add(models.SeatPricing(
                theatre_id=theatre.id, screen_id=screen.id, seat_category=category,
                base_price=round(price * PREMIUM_SCREEN_MULTIPLIER, 2),
            ))
    db.flush()


def seed_theatres(db: Session) -> Dict[str, List[models.Screen]]:
    """Returns {theatre_name: [screens]} for use by show generation."""
    print("Seeding theatres, screens, layouts, and pricing...")
    theatre_screens: Dict[str, List[models.Screen]] = {}
    for spec in THEATRES:
        theatre = get_or_create_theatre(db, spec)
        screens = [get_or_create_screen(db, theatre, s) for s in spec["screens"]]
        for screen in screens:
            ensure_published_layout(db, screen)
        ensure_seat_pricing(db, theatre, screens)
        theatre_screens[spec["name"]] = screens
    db.commit()
    print(f"  ✓ {len(THEATRES)} theatres verified/seeded.")
    return theatre_screens


# ─────────────────────────────────────────────────────────────────────────
# Movies
# ─────────────────────────────────────────────────────────────────────────
def get_or_create_movie(db: Session, spec: Dict) -> models.Movie:
    existing = (
        db.query(models.Movie)
        .filter(models.Movie.title == spec["title"], models.Movie.release_date == spec["release_date"])
        .first()
    )
    if existing:
        return existing

    is_upcoming = spec["release_date"] > date.today()
    movie = models.Movie(
        title=spec["title"], genre=spec["genre"], language=spec["language"],
        format="2D", release_date=spec["release_date"],
        running_days=90, poster_url=None, description=spec["description"],
        duration=spec["duration"], rating=spec["rating"],
        status="Coming Soon" if is_upcoming else "Now Showing",
        is_deleted=False,
    )
    db.add(movie)
    db.flush()
    return movie


def seed_movies(db: Session) -> List[models.Movie]:
    print("Seeding movies...")
    movies = [get_or_create_movie(db, spec) for spec in MOVIES]
    db.commit()
    print(f"  ✓ {len(MOVIES)} movies verified/seeded.")
    return movies


# ─────────────────────────────────────────────────────────────────────────
# Shows
# ─────────────────────────────────────────────────────────────────────────
def get_or_create_show(
    db: Session, movie: models.Movie, screen: models.Screen,
    show_date: date, start_time: str,
) -> Optional[models.Show]:
    existing = (
        db.query(models.Show)
        .filter(
            models.Show.screen_id == screen.id, models.Show.movie_id == movie.id,
            models.Show.date == show_date, models.Show.start_time == start_time,
        )
        .first()
    )
    if existing:
        return None

    # Never overlap another show already scheduled on this screen/date/time.
    clash = (
        db.query(models.Show)
        .filter(models.Show.screen_id == screen.id, models.Show.date == show_date, models.Show.start_time == start_time)
        .first()
    )
    if clash:
        return None

    start_h, start_m = (int(x) for x in start_time.split(":"))
    runtime = movie.duration or 150
    end_dt = datetime(2000, 1, 1, start_h, start_m) + timedelta(minutes=runtime + 25)
    end_time = end_dt.strftime("%H:%M")

    show = models.Show(
        movie_id=movie.id, screen_id=screen.id, date=show_date,
        start_time=start_time, end_time=end_time, price_multiplier=1.0,
    )
    db.add(show)
    db.flush()
    return show


def seed_shows(db: Session, movies: List[models.Movie], theatre_screens: Dict[str, List[models.Screen]]) -> int:
    """Curated, non-combinatorial show distribution:
    - Never for unreleased movies (release_date must be <= today).
    - Classics get a small number of retrospective screenings (1-2 theatres).
    - Current/recent movies get broader distribution across language-affine
      cities, several dates, but not every theatre in every city.
    """
    print("Seeding shows (skipping any movie not yet released)...")
    today = date.today()

    # theatre_name -> city, for filtering by language affinity
    theatre_city = {spec["name"]: spec["city"] for spec in THEATRES}

    created = 0
    for movie in movies:
        if movie.release_date is None or movie.release_date > today:
            continue  # never schedule shows for unreleased movies

        is_classic = movie.release_date < date(2020, 1, 1)
        target_cities = LANGUAGE_CITY_AFFINITY.get(movie.language, [])
        if not target_cities:
            continue

        # Candidate theatres in the movie's affine cities.
        candidate_theatres = [name for name, city in theatre_city.items() if city in target_cities]
        if not candidate_theatres:
            continue

        if is_classic:
            chosen_theatres = candidate_theatres[:2]
            dates_offsets = [3]  # a single retrospective date, ~3 days out
            slots = [SHOW_TIME_SLOTS[1]]  # one afternoon slot
        else:
            chosen_theatres = candidate_theatres[:5]
            dates_offsets = [1, 4, 8]
            slots = SHOW_TIME_SLOTS[:3]

        for theatre_name in chosen_theatres:
            screens = theatre_screens.get(theatre_name, [])
            if not screens:
                continue
            for i, offset in enumerate(dates_offsets):
                show_date = today + timedelta(days=offset)
                screen = screens[i % len(screens)]
                slot = slots[i % len(slots)]
                show = get_or_create_show(db, movie, screen, show_date, slot)
                if show:
                    created += 1
    db.commit()
    print(f"  ✓ {created} new shows created.")
    return created


# ─────────────────────────────────────────────────────────────────────────
def seed_catalog():
    print("Creating tables (no-op if already present)...")
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        handle_synthetic_placeholder(db)
        db.commit()

        theatre_screens = seed_theatres(db)
        movies = seed_movies(db)
        seed_shows(db, movies, theatre_screens)

        print("Demo catalog seeding complete!")
    except Exception as e:
        print(f"Error seeding demo catalog: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_catalog()
